### ISSUE TITLE
Uploading documents in set redirect issue

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-dms#169]
When uploading documents inside a document set in the document model admin you are then redirected back to the 'Document' tab. Instead, you should be redirected inside that particular document set where you can view the documents you just uploaded.

**Comment by sachajudd** [comment]
This behaviour doesn't exist yet, needs to be resolved in #168

**Comment by fspringveldt** [comment]
@sachajudd I'm re-opening this issue as it's related to DMSDocumentAddController::Backlink() method and not to 168. I'll raise a separate issue for accordingly.

**Comment by robbieaverill** [comment]
Can we have some steps to reproduce on the current master branch?

**Comment by fspringveldt** [comment]
@robbieaverill sure>
1. Okay, sign in as admin
2. Click Documents model admin, then Document Tab. Click ‘Add Document’ and upload a ticket
3. Now click ‘Done’ at the bottom, and you get taken incorrectly to the ‘Document Set’ tab. This is wrong, and the problem is in DMSDocumentAddController->Backlink()

**Comment by robbieaverill** [comment]
Thanks, valid issue in master
