### ISSUE TITLE
"Not Found" adding first document to a new set

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-dms#175]
Uploading the _very_ first document into the _very_ first new document set either from pages or document model admin after pressing done and 'Okay' to the dialog pop-up message, an error pops up on the right-hand side saying 'Not Found'. Very temperamental. 

<img width="1322" alt="not found" src="https://user-images.githubusercontent.com/24258161/27063188-46d8bca6-5044-11e7-8d5f-f99eefa915f7.png">

**Comment by robbieaverill** [comment]
Needs more investigation to try and find out what causes this. I can't reproduce it in either page or document ModelAdmin context using those steps.

**Comment by robbieaverill** [comment]
Steps to reproduce:

* Log in to the CMS
* Load a page (this is what creates the problem)
* Go to "Documents" ModelAdmin
* Go to Document Sets, create a new set
* Enter a name, do not enter a page
* Save
* Add document to the set
* Upload document
* Save

This only happens when you've previously had a page loaded, because it's trying to associate it to the "current page ID" from the session. If you log in fresh and don't load the edit screen for a page, the above steps will work.
