### ISSUE TITLE
can't change default storage folder location

### ISSUE THREAD

**Issue by mithun-prasannan** [silverstripe/silverstripe-dms#186]
Hi there,

As per the documentation https://github.com/silverstripe/silverstripe-dms/blob/master/docs/en/configuration.md#changing-the-default-storage-folder we tried to change the storage location to 'assets/_dmassets' but it seems to be defaulting to 'assets/Uploads' which means the uploaded document doesn't get stored in the DMS.

We are currently using DMS-2.0.1 and we are on recipe 1.5.2.

Regards,
Mithun.

**Comment by robbieaverill** [comment]
Thanks @mithun-prasannan - will investigate shortly

**Comment by wakes** [comment]
@robbieaverill @mithun-prasannan some more info about this. It looks like it may be a CWP recipe only config issue in that CWP configures Injector to use a SelectUploadField instead of an UploadField, however we really want the DMS module's DMSUploadField to be used instead as that does the moving of things into the assets folder after upload?

so cwp/_config/config.yml:36 has configured

```
Injector:
  UploadField: SelectUploadField
```

Which I think is causing the DMSUploadField::create(...) method in the DMSDocumentAddController to return the SelectUploadField instead of a DMSUploadField. The SelectUploadField uses a FolderDropdownField to store the folder which defaults to the last folder selected (from Session) which doesn't allow you then to configure the folder to upload to if a folder was ever selected before by the looks of things.

**Comment by wakes** [comment]
@robbieaverill we have worked around by configuring injector to use a class derived from DMSUploadField for the DMSUploadField (probably don't need to to that but should skip config ordering by doing so) and appears to work.

class:

```
class CustomDMSUploadField extends DMSUploadField {
}

```
in a config.yml:

```
Injector:
  DMSUploadField:
    class: CustomDMSUploadField
```

**Comment by robbieaverill** [comment]
Thanks for the investigation @wakes - you're right, in that it turns out that the injector in SS 3.x will return a class if the parent is overloaded but not the child. I've submitted a patch PR for this at #189, will release it as 2.0.2 once merged.

**Comment by wakes** [comment]
@robbieaverill cool thanks robbie

**Comment by robbieaverill** [comment]
@wakes @mithun-prasannan 2.0.2 released with this fix, thanks for reporting!
