### ISSUE TITLE
Permissions on dms-assets

### ISSUE THREAD

**Issue by andylockran** [silverstripe/silverstripe-dms#42]
Hey guys,

If dms-assets isn't writable by the webserver, then the upload doesn't fail gracefully.  To the end user it looks like the document has been successfully uploaded.  Any ideas why this should be the case by default?

**Comment by robbieaverill** [comment]
Hi @andylockran - this is fixed in the 2.x release (to be released soon) in that:

* The dms-assets folder has been moved into the regular assets folder
* If that folder is not writeable then it's a framework/web server issue more than this module

If you're interested in submitting a patch to fix this in the 1.x release line of DMS a pull request is welcome, and feel free to reopen this issue. For now it's fixed in #98.
