### ISSUE TITLE
Unable to edit file immediately after uploading

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-dms#53]
When attaching files to a page using the “AssetUploadField” view, if you click the “Edit” button after uploading you’ll get a server error:

> Argument 1 passed to UploadField::getFileEditFields() must be an instance of File, instance of DMSDocument given

I’m not sure if this can actually be fixed in this module. Screenshot attached of the view I’m referring to.

![screen shot 2014-09-18 at 10 01 03](https://cloud.githubusercontent.com/assets/1655548/4317363/593f26c8-3f12-11e4-8e94-ce65ab4bf950.png)

**Comment by jaedb** [comment]
Has there been any progress on properly fixing this? @dhensby

**Comment by dhensby** [comment]
@kinglozzer  ?

**Comment by dhensby** [comment]
@jaedb to answer more explicitly, I don't have a clue - I'm only lightly involved in maintaining DMS and don't actually use it in production. 

This issue is coming up to 2 years old so you'd like to think it's fixed, but I guess you're asking because it's not?

I'd have thought this is more an underlying framework issue than a DMS one, but I haven't looked into it, I'm afraid.

**Comment by jaedb** [comment]
@dhensby I suspect the issue has flown under the radar because it's not causing critical errors. However I suspect the later versions of Silverstripe are becoming more sensitive to the issue. SS 3.3.2 + DMS just don't work well at all together.

It seems to me that the root cause is a combination of `UploadField` wanting a `File` object, and `DMSDocument` extending `DataObject`. This means DMS is always going to require hack fixes until it extends the `File` object or `UploadField` becomes more flexible.

**Comment by kinglozzer** [comment]
Sorry, my memory of this module is really patchy! I think you’re correct @jaedb - the issue is to do with `UploadField` expecting an instance of `File` - hence why I had to remove the type-hinting by naming the validator/action/field methods something else :/

I have no idea how best to approach fixing this, though...

**Comment by xini** [comment]
I think @benmanu has a fix at https://github.com/benmanu/silverstripe-dms/commit/a5e2d29e9c80d7eea9f6825764c50b8ea360e9ca?

**Comment by dhensby** [comment]
PR @benmanu?
